openapi: "3.0.0"
info:
  version: 1.0.0
  title: Stop COVID
  description: Ma super API contre le COVID
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
    /profile:
        post:
            tags:
            - "profile"
            summary: "On veut créer un profile avec tous les attributs cités dans l'ennoncé, on met le nom et email en required"
            parameters:
            - in: "body"
            name: "body"
            description: "Profil devant être ajouté"
            required: true
            schema:
            $ref:'#components/schemas/Profile'
            
        put:
            tags:
            - "profile"
            summary: "On veut MAJ un profile"
            parameters:
            - in: "body"
            name: "body"
            description: "On modifie un profil"
            required: true
            schema:
                $ref:'#components/schemas/Profile'
           
    /contact/{name}
        get:
            tags:
            - "contact"
            summary:" "
            parameters:
            - name: "name"
                in: "path"
                required:true
                type:string
            response:
            schema:
                $ref:'#components/schemas/Contact'

    
    /contact/{email}
        get:
        tags:
        - "contact"
        summary:""
        parameters:
        - name: "email"
            in: "path"
            required:true
            type:string   
            response:
            schema:
                $ref:'#components/schemas/Contact' 
                
    /contact/{email}
        delete:
        tags:
        - "contact"
        summary:""
        parameters:
        - name: "email"
            in: "path"
            required:true
            type:string   
            response:
                description:"deleted"
    /contact/{email}
        put:
        tags:
         - "contact"
            summary: ""
            parameters:
            - in: "body"
            name: "body"
            description: "On modifie un contact qu'on trouve par email"
            required: true
            response:
            schema:
                $ref:'#components/schemas/Contact'
             
    /cas
        post:
        tags:
        - "cas"
            summary: "Je déclarer un cas avec une personne"
            parameters:
            - in: "body"
            name: "body"
            description: "cas devant être ajouté"
            required: true
            schema:
            $ref:'#components/schemas/Cas'
            
    /cas/{contact}
        get:
        tags:
        - "cas"
        summary:"on cherche un contact avec qui on a eu un cas déclaré"
        parameters:
        - name: "contact"
            in: "path"
            required:true
            type:string 
            response:
            schema:
                $ref:'#components/schemas/Cas'  
       
    /declaration
        post:
        tags:
        - "declaration"
            summary: "Je déclarer que j'ai ete contamine"
            parameters:
            - in: "body"
            name: "body"
            description: "ma contamination"
            required: true
            schema:
            $ref:'#components/schemas/Declaration'
            
    
    /administrateur/profile/{name}
     get:
        tags:
        - "profile"
        summary:""
        parameters:
        - name: "name"
            in: "path"
            required:true
            type:string 
            response:
            schema:
                $ref:'#components/schemas/Profile/name'
                $ref:'#components/schemas/Profile/first_name'
                $ref:'#components/schemas/Profile/email'
       
    /administrateur/profile/{idprofile}
     get:
        tags:
        - "profile"
        summary:""
        parameters:
        - name: "idprofile"
            in: "path"
            required:true
            type:int 
            response:
            schema:
                $ref:'#components/schemas/Profile/name'
                $ref:'#components/schemas/Profile/first_name'
                $ref:'#components/schemas/Profile/email'

       
    /administrateur/profile/{name}
     get:
        tags:
        - "profile"
        summary:""
        parameters:
        - name: "name"
            in: "path"
            required:true
            type:string 
            response:
            schema:
                $ref:'#components/schemas/Profile'
                
    /administrateur/profile/{idprofile}
     get:
        tags:
        - "profile"
        summary:""
        parameters:
        - name: "idprofile"
            in: "path"
            required:true
            type:int 
            response:
            schema:
                $ref:'#components/schemas/Profile'
                
    
    /administrateur/profile/{idprofile}/contact
     get:
        tags:
        - "profile"
        - "contact"
        summary:""
        parameters:
        - name: "idprofil"
            in: "path"
            required:true
            type:int 
            response:
            schema:
                $ref:'#components/schemas/Contact'
                
    /administrateur/profile/{idprofile}/contact
     get:
        tags:
        - "profile"
        - "contact"
        summary:""
        parameters:
        - name: "idprofil"
            in: "path"
            required:true
            type:int 
            response:
            schema:
                $ref:'#components/schemas/Contact'
                
    /administrateur/alerte/contact/
        post:
        tags:
        - "declaration"
            summary: ""
            parameters:
            - in: "body"
            name: "body"
            description: ""
            required: true
            schema:
            $ref:'#components/schemas/Alertes'
            $ref:'#components/Contact/id_contact'
         
    
components:
schemas:
    Profile:
    type: object
    required:
    - name
    - email
        properties:
            name:
                type: string
            firstname:
                type: string
            age:
                type: integer
            address:
                type: string
            email:
                type:string
            covid_state: boolen
            number_of_contact: int
    Contact:
    type : object
        properties:
            id_contact:
                type: int
            name:
                type: string
            firstname: string
            email: string
    Cas:
    type: object
        properties:
            id_cas:
                type:int
            date: 
                type: date
            time: 
                type :time
            location: 
                type :string
            typeofcontact: 
                type: string
            contact:
                type: $ref:'#components/schemas/Contact' 
            
    Declaration:
    type:object
       properties:
       id_declaration:
            type: int
        profile: 
            type:profile
        date_test:
            type:date
    
    Alerte:
        properties:
            id_alerte:
                type:int
            id_malade:
                type : int
            date_contact :
                type : date
            
    