swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Swagger TP COVID"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "profilestore.swagger.io"
basePath: "/v2"
tags:
- name: "profile"
  description: "Everything about your Profiles"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /profile:
    post:
      tags:
      - "profile"
      summary: "Create a new profile"
      description: ""
      operationId: "addProfile"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Profile object that needs to be created"
        required: true
        schema:
          $ref: "#/definitions/Profile"
      responses:
        "405":
          description: "Invalid input"
    put:
      tags:
      - "profile"
      summary: "Update an existing profile"
      description: ""
      operationId: "updateProfile"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Profile object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Profile"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Profile not found"
        "405":
          description: "Validation exception"
  /profile/findByLastname:
    get:
      tags:
      - "profile"
      summary: "Search a profil by lastname"
      description: ""
      operationId: "searchProfilByLastname"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "lastname"
        in: "query"
        description: "Profile object that needs to be created"
        required: true
        type: "string"
      responses:
        "405":
          description: "Invalid input"
  /profile/findByEmail:
    get:
      tags:
      - "profile"
      summary: "Search a profil by email"
      description: ""
      operationId: "searchProfilByEmail"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "mail"
        in: "query"
        description: "Profile object that needs to be created"
        required: true
        type: "string"
      responses:
        "405":
          description: "Invalid input"
  /contact:
    post:
      tags:
      - "contact"
      summary: "Create contact"
      description: ""
      operationId: "createContact"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created contact object"
        required: true
        schema:
          $ref: "#/definitions/Contact"
      responses:
        default:
          description: "successful operation"
definitions:
  Profile:
    type: "object"
    required:
      - "lastname"
      - "mail"
    properties:
      id:
        type: "integer"
        format: "int64"
      firstname:
        type: "string"
      lastname:
        type: "string"
      age:
        type: "integer"
        format: "int64"
      mail:
        type: "string"
        format: "email"
  Contact:
    type: "object"
    required:
    - "datetime"
    properties:
      id:
        type: "integer"
        format: "int64"
      datetime:
        type: "string"
        format: "date-time"
      location:
        type: "string"
      contactType:
        type: "string"
        enum:
        - "withMask"
        - "withoutMask"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"