openapi: "3.0.0"
info:
  version: 1.0.0
  title: Stop COVID
  description: Ma super API contre le COVID
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/

paths:
  /Profile:
     post:
      requestBody:
        description: Add a Profile
        content: 
          'application/json':
            schema:
              $ref: '#/components/schemas/Profile'
      
      responses:
        '200':
          description: Profile add with success
        '405':
          description: Invalid input"
  
  /Profile/{profileId}:
     put:
      requestBody:
        description: Add a Profile
        content: 
          'application/json':
            schema:
              $ref: '#/components/schemas/Profile'
      parameters:
        - in: path
          name: profileId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Profile add with success
        '405':
          description: Invalid input"
  /Contact:
     get:
      tags:
      - "AllContact"
      summary: "Finds Contact"
      description: "All Contacts declared"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"
     put:
      requestBody:
        description: Add a Contact
        content: 
          'application/json':
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '200':
          description: Contact Add with success
        '405':
          description: Invalid input"
      
  /Contact/{contactId}:
     put:
      requestBody:
        description: Update a Contact
        content: 
          'application/json':
            schema:
              $ref: '#/components/schemas/Contact'
      parameters:
        - in: path
          name: contactId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Contact update with success
        '405':
          description: Invalid input"
          
     delete:
      tags:
      - "deleteContact"
      summary: "Deletes a profile"
      description: ""
      parameters:
          - in: path
            name: contactId
            schema:
              type: integer
            required: true
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Contact not found"
          
  /User:
     get:
      tags:
      - "AllUser"
      summary: "Finds All User"
      description: "All User declared"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"
     put:
      requestBody:
        description: Add a User
        content: 
          'application/json':
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User Add with success
        '405':
          description: Invalid input"
          
  /User/{userId}:
     get:
      tags:
        - "OneUser"
      summary: "Finds User By Id"
      description: "One User declared"
      parameters:
      - in: path
        name: userId
        schema:
          type: integer
        required: true
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"
          
      patch:
       tags:
        - "DeclareMalade"
       summary: "Se déclarer malade"
       description: "se déclarer malade"
       parameters:
       - in: path
         name: userId
         schema:
           type: integer
         required: true
       responses:
         "200":
           description: "successful operation"
         "400":
           description: "Invalid status value"
          
  /User/{userId}/Contact:
     get:
      tags:
        - "ContactOfOneUser"
      summary: "Contact of one User By Id"
      description: "Contact of one User By Id"
      parameters:
      - in: path
        name: userId
        schema:
          type: integer
        required: true
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid status value"
        
components:
  schemas:
    Profile:
      type: object
      required:
        - name
        - email
      properties:
        profileId:
          type: integer
        name:
          type: string
        firstname:
          type: string
        age:
          type: integer
        address:
          type: string
        email:
          type: string
        adresse:
          type: string
        statutCOVID:
          type: string
          enum:
          - "Malade"
          - "NonMalade"
        nbContact:
          type: integer
    User:
      type: object
      required:
        - userId
      properties:
        userId:
          type: integer
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
    Contact:
      type: object
      required:
        - contactId
      properties:
        contactId:
          type: integer
        DateTime:
          type: string
        Lieu:
          type: string
        masque:
          type: string
          enum:
          - "Avec"
          - "Sans"
        othercontactId:
          type: integer

